I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/chapter08.rpy", line 18, in script
    $renge.pause(1)
  File "game/chapter08.rpy", line 18, in <module>
    $renge.pause(1)
NameError: name 'renge' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/chapter08.rpy", line 18, in script
    $renge.pause(1)
  File "/home/rafaelb/Público/Renpy/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/rafaelb/Público/Renpy/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/chapter08.rpy", line 18, in <module>
    $renge.pause(1)
NameError: name 'renge' is not defined

Linux-5.13.0-51-generic-x86_64-with-debian-bullseye-sid
Ren'Py 7.4.11.2266
Trigger World 1.0
Sun Jun 26 18:28:12 2022
